log = "./log/"
secret = ""
producers = []

[p2p]
enable = true
bind = "0.0.0.0:30000"
peers = []

persist_len = 30
persist_path = "./peers"

max_bases = 32
max_peers = 32
max_tasks = 1024
max_temp = 32

ms_log = 20000
ms_peers = 60000
ms_outbound = 30000
ms_bases = 60000
ms_ping = 300000

[esl]
enable = true
bind = "0.0.0.0:1234"
ms_log = 5000