log = "./log/"
secret = ""
producers = []

max_msg = 65536
max_msgs = 10000

[p2p]
enable = true
bind = "0.0.0.0:30000"
peers = []

persist_len = 30
persist_path = "./peers"

max_temp = 32
max_peers = 32

ms_log = 30000
ms_peers = 60000
ms_outbound = 30000
ms_bases = 60000
ms_ping = 300000
ms_task = 10

[esl]
enable = true
bind = "0.0.0.0:1234"

max_clients = 1024

ms_log = 35000
ms_task = 1000